import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CartProvider } from "@/context/CartContext";
import CursorTrail from "@/components/CursorTrail";
import HellfireBackground from "@/components/HellfireBackground";
import LoadingScreen from "@/components/LoadingScreen";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#080304] text-white relative">
        <CartProvider>
          <HellfireBackground />
          <CursorTrail />
          <LoadingScreen />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
